# Generated by Django 4.2.2 on 2023-06-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectPizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches', models.PositiveIntegerField(default=1)),
                ('awards', models.PositiveIntegerField(default=1)),
                ('customer', models.PositiveIntegerField(default=1)),
                ('staff', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Pizza Number',
                'verbose_name_plural': 'Pizza Number',
            },
        ),
    ]
